export const FETCH_USER_SEARCH = "FETCH_USER_SEARCH";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const TOOGLE_FAVORITES = "TOOGLE_FAVORITES"

